export const ADD_LOCAL_WEATHER = 'ADD_LOCAL_WEATHER'
export const ADD_LOCAL_SELECTED_DAY = 'ADD_LOCAL_SELECTED_DAY'
export const ADD_COUNTRY_WEATHER ='ADD_COUNTRY_WEATHER'
export const ADD_COUNTRY_SELECTED_DAY= 'ADD_COUNTRY_SELECTED_DAY'